FROM python:3.11-slim

WORKDIR /app

COPY . .

RUN pip install --no-cache-dir -r requirements.txt


RUN python -m grpc_tools.protoc -I. --python_out=. --grpc_python_out=. posts.proto

CMD ["python", "server.py"]
