# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: posts.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'posts.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bposts.proto\x12\x04post\"m\n\x11\x43reatePostRequest\x12\r\n\x05title\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x12\n\ncreator_id\x18\x03 \x01(\x05\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\"2\n\x0eGetPostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x14\n\x0crequester_id\x18\x02 \x01(\x05\"y\n\x11UpdatePostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\nis_private\x18\x04 \x01(\x08\x12\x0c\n\x04tags\x18\x05 \x03(\t\x12\x12\n\nupdater_id\x18\x06 \x01(\x05\"3\n\x11\x44\x65letePostRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\ndeleter_id\x18\x02 \x01(\x05\"I\n\x10ListPostsRequest\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\x11\n\tpage_size\x18\x02 \x01(\x05\x12\x14\n\x0crequester_id\x18\x03 \x01(\x05\"\x9c\x01\n\x0cPostResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x03 \x01(\t\x12\x12\n\ncreator_id\x18\x04 \x01(\x05\x12\x12\n\ncreated_at\x18\x05 \x01(\t\x12\x12\n\nupdated_at\x18\x06 \x01(\t\x12\x12\n\nis_private\x18\x07 \x01(\x08\x12\x0c\n\x04tags\x18\x08 \x03(\t\"%\n\x12\x44\x65letePostResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\x11ListPostsResponse\x12!\n\x05posts\x18\x01 \x03(\x0b\x32\x12.post.PostResponse2\xb7\x02\n\x0bPostService\x12\x39\n\nCreatePost\x12\x17.post.CreatePostRequest\x1a\x12.post.PostResponse\x12\x33\n\x07GetPost\x12\x14.post.GetPostRequest\x1a\x12.post.PostResponse\x12\x39\n\nUpdatePost\x12\x17.post.UpdatePostRequest\x1a\x12.post.PostResponse\x12?\n\nDeletePost\x12\x17.post.DeletePostRequest\x1a\x18.post.DeletePostResponse\x12<\n\tListPosts\x12\x16.post.ListPostsRequest\x1a\x17.post.ListPostsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'posts_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CREATEPOSTREQUEST']._serialized_start=21
  _globals['_CREATEPOSTREQUEST']._serialized_end=130
  _globals['_GETPOSTREQUEST']._serialized_start=132
  _globals['_GETPOSTREQUEST']._serialized_end=182
  _globals['_UPDATEPOSTREQUEST']._serialized_start=184
  _globals['_UPDATEPOSTREQUEST']._serialized_end=305
  _globals['_DELETEPOSTREQUEST']._serialized_start=307
  _globals['_DELETEPOSTREQUEST']._serialized_end=358
  _globals['_LISTPOSTSREQUEST']._serialized_start=360
  _globals['_LISTPOSTSREQUEST']._serialized_end=433
  _globals['_POSTRESPONSE']._serialized_start=436
  _globals['_POSTRESPONSE']._serialized_end=592
  _globals['_DELETEPOSTRESPONSE']._serialized_start=594
  _globals['_DELETEPOSTRESPONSE']._serialized_end=631
  _globals['_LISTPOSTSRESPONSE']._serialized_start=633
  _globals['_LISTPOSTSRESPONSE']._serialized_end=687
  _globals['_POSTSERVICE']._serialized_start=690
  _globals['_POSTSERVICE']._serialized_end=1001
# @@protoc_insertion_point(module_scope)
