version: '3.8'
services:
  # СУБД (PostgreSQL)
  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - my_network

  # Сервис пользователей (Python, FastAPI)
  user-service:
    build: ./user_service
    container_name: user-service
    environment:
      DATABASE_URL: "postgresql://postgres:postgres@user-db:5432/postgres"
      SECRET_KEY: "supersecretkey"
    depends_on:
      - user-db
    ports:
      - "8001:8001"
    networks:
      - my_network

  # Proxy-сервис (Node.js, Express)
  api-service:
    build: ./api_service
    container_name: api-service
    depends_on:
      - user-service
    ports:
      - "8000:8000"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge